name: Java CI with Maven

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21.0.2'

      - name: Install Maven 3.9.9
        run: sudo apt-get install -y wget maven

      - name: Build with Maven
        run: mvn clean test
